# Generated by Django 6.0.2 on 2026-02-18 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=100, verbose_name='name (Persian)')),
                ('name_en', models.CharField(max_length=100, verbose_name='name (English)')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='icon class')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'Project Category',
                'verbose_name_plural': 'Project Categories',
                'ordering': ['order', 'name_fa'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=200, verbose_name='title (Persian)')),
                ('title_en', models.CharField(max_length=200, verbose_name='title (English)')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description_fa', models.TextField(verbose_name='description (Persian)')),
                ('description_en', models.TextField(verbose_name='description (English)')),
                ('short_description_fa', models.CharField(max_length=300, verbose_name='short description (Persian)')),
                ('short_description_en', models.CharField(max_length=300, verbose_name='short description (English)')),
                ('featured_image', models.ImageField(upload_to='projects/', verbose_name='featured image')),
                ('gallery', models.JSONField(blank=True, default=list, verbose_name='gallery images')),
                ('client_name', models.CharField(blank=True, max_length=200, verbose_name='client name')),
                ('project_url', models.URLField(blank=True, verbose_name='project URL')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('technologies', models.JSONField(blank=True, default=list, verbose_name='technologies used')),
                ('features_fa', models.JSONField(blank=True, default=list, verbose_name='features (Persian)')),
                ('features_en', models.JSONField(blank=True, default=list, verbose_name='features (English)')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('planned', 'Planned')], default='completed', max_length=20, verbose_name='status')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='completion date')),
                ('is_featured', models.BooleanField(default=False, verbose_name='is featured')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='views count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio.projectcategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-is_featured', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='client name')),
                ('client_position', models.CharField(blank=True, max_length=200, verbose_name='client position')),
                ('client_company', models.CharField(blank=True, max_length=200, verbose_name='client company')),
                ('client_photo', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='client photo')),
                ('content_fa', models.TextField(verbose_name='content (Persian)')),
                ('content_en', models.TextField(verbose_name='content (English)')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='rating')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='portfolio.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'Project Testimonial',
                'verbose_name_plural': 'Project Testimonials',
                'ordering': ['-created_at'],
            },
        ),
    ]
