# Generated by Django 6.0.2 on 2026-02-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=200, verbose_name='title (Persian)')),
                ('title_en', models.CharField(max_length=200, verbose_name='title (English)')),
                ('description_fa', models.TextField(verbose_name='description (Persian)')),
                ('description_en', models.TextField(verbose_name='description (English)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='image')),
                ('video_url', models.URLField(blank=True, verbose_name='video URL')),
                ('projects_completed', models.PositiveIntegerField(default=0, verbose_name='projects completed')),
                ('happy_clients', models.PositiveIntegerField(default=0, verbose_name='happy clients')),
                ('awards_won', models.PositiveIntegerField(default=0, verbose_name='awards won')),
                ('years_experience', models.PositiveIntegerField(default=0, verbose_name='years experience')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Sections',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone1', models.CharField(max_length=20, verbose_name='phone 1')),
                ('phone2', models.CharField(blank=True, max_length=20, verbose_name='phone 2')),
                ('address_fa', models.TextField(verbose_name='address (Persian)')),
                ('address_en', models.TextField(verbose_name='address (English)')),
                ('google_maps_url', models.URLField(blank=True, verbose_name='google maps URL')),
                ('instagram', models.URLField(blank=True, verbose_name='instagram')),
                ('telegram', models.URLField(blank=True, verbose_name='telegram')),
                ('linkedin', models.URLField(blank=True, verbose_name='linkedin')),
                ('twitter', models.URLField(blank=True, verbose_name='twitter')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'Contact Info',
                'verbose_name_plural': 'Contact Info',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('subject', models.CharField(max_length=200, verbose_name='subject')),
                ('message', models.TextField(verbose_name='message')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=200, verbose_name='title (Persian)')),
                ('title_en', models.CharField(max_length=200, verbose_name='title (English)')),
                ('subtitle_fa', models.TextField(verbose_name='subtitle (Persian)')),
                ('subtitle_en', models.TextField(verbose_name='subtitle (English)')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='background image')),
                ('cta_button_text_fa', models.CharField(default='مشاهده خدمات', max_length=100, verbose_name='CTA button text (Persian)')),
                ('cta_button_text_en', models.CharField(default='View Services', max_length=100, verbose_name='CTA button text (English)')),
                ('cta_button_link', models.CharField(default='#services', max_length=200, verbose_name='CTA button link')),
                ('secondary_button_text_fa', models.CharField(default='درخواست همکاری', max_length=100, verbose_name='secondary button text (Persian)')),
                ('secondary_button_text_en', models.CharField(default='Request Collaboration', max_length=100, verbose_name='secondary button text (English)')),
                ('secondary_button_link', models.CharField(default='#contact', max_length=200, verbose_name='secondary button link')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=200, verbose_name='title (Persian)')),
                ('title_en', models.CharField(max_length=200, verbose_name='title (English)')),
                ('description_fa', models.TextField(verbose_name='description (Persian)')),
                ('description_en', models.TextField(verbose_name='description (English)')),
                ('icon', models.CharField(default='code', max_length=100, verbose_name='icon class')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='image')),
                ('technologies', models.JSONField(blank=True, default=list, verbose_name='technologies')),
                ('features_fa', models.JSONField(blank=True, default=list, verbose_name='features (Persian)')),
                ('features_en', models.JSONField(blank=True, default=list, verbose_name='features (English)')),
                ('code_snippet', models.TextField(blank=True, verbose_name='code snippet')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='key')),
                ('value', models.TextField(verbose_name='value')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=200, verbose_name='name (Persian)')),
                ('name_en', models.CharField(max_length=200, verbose_name='name (English)')),
                ('position_fa', models.CharField(max_length=200, verbose_name='position (Persian)')),
                ('position_en', models.CharField(max_length=200, verbose_name='position (English)')),
                ('bio_fa', models.TextField(blank=True, verbose_name='bio (Persian)')),
                ('bio_en', models.TextField(blank=True, verbose_name='bio (English)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='photo')),
                ('skills', models.JSONField(blank=True, default=list, verbose_name='skills')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='experience years')),
                ('projects_count', models.PositiveIntegerField(default=0, verbose_name='projects count')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('linkedin', models.URLField(blank=True, verbose_name='linkedin')),
                ('twitter', models.URLField(blank=True, verbose_name='twitter')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
